# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
Rails.application.config.assets.precompile += %w( welcome.css )
Rails.application.config.assets.precompile += %w( welcome.js )
Rails.application.config.assets.precompile += %w(welcome/bootstrap.js)
Rails.application.config.assets.precompile += %w(welcome/jquery-min.js)
Rails.application.config.assets.precompile += %w(welcome/main.js)
Rails.application.config.assets.precompile += %w(welcome/wow.js)
Rails.application.config.assets.precompile += %w(welcome/gen_validatorv4.js )

Rails.application.config.assets.precompile += %w(company.css)
Rails.application.config.assets.precompile += %w(company.js)
Rails.application.config.assets.precompile += %w(company/jquery.min.js )
Rails.application.config.assets.precompile += %w(company/bootstrap.min.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.min.js)
Rails.application.config.assets.precompile += %w(company/excanvas.min.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.resize.min.js)
Rails.application.config.assets.precompile += %w(company/jquery.peity.min.js)
Rails.application.config.assets.precompile += %w(company/fullcalendar.min.js)
Rails.application.config.assets.precompile += %w(company/matrix.calendar.js)
Rails.application.config.assets.precompile += %w(company/matrix.js)
Rails.application.config.assets.precompile += %w(company/matrix.dashboard.js)
Rails.application.config.assets.precompile += %w(company/jquery.gritter.min.js)
Rails.application.config.assets.precompile += %w(company/matrix.interface.js)
Rails.application.config.assets.precompile += %w(company/matrix.chat.js)
Rails.application.config.assets.precompile += %w(company/jquery.validate.js)
Rails.application.config.assets.precompile += %w(company/matrix.form_validation.js)
Rails.application.config.assets.precompile += %w(company/jquery.wizard.js)
Rails.application.config.assets.precompile += %w(company/jquery.uniform.js)
Rails.application.config.assets.precompile += %w(company/select2.min.js)
Rails.application.config.assets.precompile += %w(company/matrix.popover.js)
Rails.application.config.assets.precompile += %w(company/jquery.dataTables.min.js)
Rails.application.config.assets.precompile += %w(company/matrix.tables.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.pie.min.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.pie.js)
Rails.application.config.assets.precompile += %w(company/matrix.charts.js )
Rails.application.config.assets.precompile += %w(company/jquery.ui.custom.js)
Rails.application.config.assets.precompile += %w(company/masked.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.min.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.crosshair.js)
Rails.application.config.assets.precompile += %w(company/jquery.flot.stack.js)
Rails.application.config.assets.precompile += %w(company/jquery.easy-pie-chart.js)
Rails.application.config.assets.precompile += %w(company/bootstrap-colorpicker.js)
Rails.application.config.assets.precompile += %w(company/bootstrap-wysihtml5.js)
Rails.application.config.assets.precompile += %w(company/matrix.form_common.js)
Rails.application.config.assets.precompile += %w(company/matrix.login.js)
Rails.application.config.assets.precompile += %w(company/matrix.popover.js)
Rails.application.config.assets.precompile += %w(company/matrix.tables.js)
Rails.application.config.assets.precompile += %w(company/wysihtml5-0.3.0.js)






Rails.application.config.assets.precompile += %w(recruiter.css)
Rails.application.config.assets.precompile += %w(recruiter.js)
Rails.application.config.assets.precompile += %w( recruiter/jquery.min.js )
Rails.application.config.assets.precompile += %w(recruiter/bootstrap.min.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.flot.min.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.peity.min.js)
Rails.application.config.assets.precompile += %w(recruiter/fullcalendar.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.js)
Rails.application.config.assets.precompile += %w(recruiter/excanvas.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.dashboard.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.gritter.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.interface.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.chat.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.validate.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.form_validation.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.wizard.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.uniform.js)
Rails.application.config.assets.precompile += %w(recruiter/select2.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.popover.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.dataTables.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.tables.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.ui.custom.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.flot.pie.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.charts.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.flot.resize.min.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.calendar.js)
Rails.application.config.assets.precompile += %w(recruiter/masked.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.flot.min.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.flot.crosshair.js)
Rails.application.config.assets.precompile += %w(recruiter/jquery.easy-pie-chart.js)
Rails.application.config.assets.precompile += %w(recruiter/bootstrap-colorpicker.js)
Rails.application.config.assets.precompile += %w(recruiter/bootstrap-wysihtml5.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.form_common.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.login.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.popover.js)
Rails.application.config.assets.precompile += %w(recruiter/matrix.tables.js)
Rails.application.config.assets.precompile += %w(recruiter/wysihtml5-0.3.0.js)
Rails.application.config.assets.precompile += %w(recruiter/gen_validatorv4.js )